close all;
allTests = {'PositiveViZero', 'PositiveViZeroPlateau', ...
            'PositiveViPositive', 'PositiveViPositivePlateau', ...
            'PositiveViAbove', 'PositiveViAbovePlateau', ...
            'PositiveViPositiveOvershot', 'PositiveViPositiveOvershotPlateau', ...
            'PositiveViNegativeOvershot', 'PositiveViNegativeOvershotPlateau', ...
            'NegativeViZero', 'NegativeViZeroPlateau', ...
            'NegativeViNegative', 'NegativeViNegativePlateau', ...
            'NegativeViBelow', 'NegativeViBelowPlateau',  ...
            'NegativeViNegativeOvershot', 'NegativeViNegativeOvershotPlateau', ...
            'NegativeViPositiveOvershot', 'NegativeViPositiveOvershotPlateau'};
for index = 1:numel(allTests)
    test = allTests(index);
    filename = char(strcat('robLSPB', test, '.txt'));
    figure('name', filename);
    data = load(filename);
    plot(data(:,1), data(:,3), data(:,1), data(:,5), data(:,1), data(:,7));
end

data = load('robLSPBMultipleJoints.txt');
figure('name', 'robLSPBMultipleJointsPosition');
plot(data(:,1), data(:,3), data(:,1), data(:,4), data(:,1), data(:,5), ...
     data(:,1), data(:,6), data(:,1), data(:,7), data(:,1), data(:,8));
figure('name', 'robLSPBMultipleJointsVelocity');
plot(data(:,1), data(:,10), data(:,1), data(:,11), data(:,1), data(:,12), ...
     data(:,1), data(:,13), data(:,1), data(:,14), data(:,1), data(:,15)); 
figure('name', 'robLSPBMultipleJointsAcceleration');
plot(data(:,1), data(:,17), data(:,1), data(:,18), data(:,1), data(:,19), ...
     data(:,1), data(:,20), data(:,1), data(:,21), data(:,1), data(:,22));
