close all;
allTests = {'PositiveViZero', 'PositiveViZeroPlateau', ...
            'PositiveViPositive', 'PositiveViPositivePlateau', ...
            'PositiveViPositiveOvershot', 'PositiveViPositiveOvershotPlateau', ...
            'PositiveViNegativeOvershot', 'PositiveViNegativeOvershotPlateau', ...
            'NegativeViZero', 'NegativeViZeroPlateau', ...
            'NegativeViPositive', 'NegativeViPositivePlateau'};
for index = 1:numel(allTests)
    test = allTests(index);
    filename = char(strcat('robLSPB', test, '.txt'));
    figure('name', filename);
    data = load(filename);
    plot(data(:,1), data(:,3), data(:,1), data(:,5), data(:,1), data(:,7));
end